### ISSUE TITLE
Prefixing not working when multiple attributes in a single tag need to be replaced

### ISSUE THREAD

**Issue by briantjacobs** [cainiaokan/gulp-url-prefixer#1]
Ive tested the following examples, and there is one case that does not work for me when using a custom attribute (data-src). The expectation is that all relevant attributes in a tag should be prefixed. I've tried ruling out the fact that i'm also using data urls.

I'm using the following settings:
```
prefixer.html({
            prefix: "http://prefix.com/,
            tags: ['script', 'link', 'a', 'img', 'embed'],
            attrs: ['href', 'src', 'data-src']
        })
```

✅  Works (single attr, ignore the base64 data url)

```
<img src='data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw==' />
```

✅  Works (single attr)
```
<img src='http://prefix.com/build-2017-06-28_16-01-50/img.jpg' />
```

✅  Works (custom single attr)
```
<img data-src='http://prefix.com/img.jpg' />
```

✅  Works (multiple attrs within tags, second attr ok to be ignored)
```
<img data-src='http://prefix.com/img.jpg' src='data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw==' />
```
❌  NOT working (multiple attrs, second attr wants to be prefixed)
```
<img src='data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw==' data-src='img.jpg' />
```

❌  NOT working (multiple attrs, all attrs want to be prefixed)
```
<img src='http://prefix.com/img.jpg' data-src='img.jpg'  />
```

**Comment by cainiaokan** [comment]
Hi,

Thank you for your feedback.  I never expect there will be any though.😂
Anyway. As to your problem, I personally presumed that there's only one
attribute in an element tag needs to be prefixed.
Since you bring this forward and it only requires a little bit effort to
take, i'will be sure to fix this problem.

PLEASE BE AWARE. Any url that is already starts with a
scheme(http,https,etc) or a base64 declaration, it WILL BE ignored.

**Comment by cainiaokan** [comment]
Please update this plugin to v0.0.6. If everything works well, I bet your
problem will be solved.

**Comment by briantjacobs** [comment]
Thanks so much for making the fix. I can confirm this works great.
